### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by d-diaz** [mlysy/pfjax#23]
I am interested in using and expanding on pfjax, but you have no license. Can you please identify one?

Here’s some helpful info from [GitHub about licensing](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#). Of note:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and **no one may reproduce, distribute, or create derivative works from your work**. If you're creating an open source project, we strongly encourage you to include an open source license.

**Comment by mlysy** [comment]
First of all, I'm delighted that pfjax is something which might be useful to you!  As for the license, it's MIT as per `setup.cfg`: https://github.com/mlysy/pfjax/blob/cec37d01deb28281da89d83ff582c0cc034d4e62/setup.cfg#L14

That being said, I'm noticing now that the MIT license requires that the copyright notice for the original software to be included in all copies of it.  So for that purpose I'll add a LICENSE file to the repo.  Please give me a few days to do that for this multi-author project.  In the meantime, you're legally permitted to use/modify/etc the package as you wish, just not create a public fork, I guess...

**Comment by d-diaz** [comment]
Maybe it makes more sense to license this to `PFJAX Contributors` rather than an individual?

**Comment by mlysy** [comment]
Yes, that's the one :)  License added.
